version: '2'

services:

 nodepki:
  image: adito/nodepki-docker
  ports:
   - 5001:5000
  volumes:
   - certs:/certs
   - data:/root/nodepki/data
   - data:/root/nodepki-client/data
   - data:/root/nodepki-webclient/data
   - ./docker-nodepki/applications/nodepki/data/config:/root/nodepki/data/config
   - ./docker-nodepki/applications/nodepki-client/data/config:/root/nodepki-client/data/config
   - ./docker-nodepki/applications/nodepki-webclient/data/config:/root/nodepki-webclient/data/config
   - ./docker-nodepki/applications/nodepki-webclient/api/webclient/controllers/request.js:/root/nodepki-webclient/controllers/request.js
   - ./conf/http_server.conf:/etc/supervisor/conf.d/http_server.conf
  environment:
   - API_USERNAME=${API_USERNAME}
   - API_PASSWORD=${API_PASSWORD}

 nexus:
  image: clearent/nexus:latest
  restart: always
  volumes:
   - nexus-data:${NEXUS_DATA}
   - certs:/certs
   - ./etc/nexus.properties:/opt/sonatype/sonatype-work/nexus3/etc/nexus.properties
  environment:
   - JKS_PASSWORD=${JKS_PASSWORD}
  ports:
   - 443:8443
   - 8081:8081
   - 5000:5000

volumes:
 nexus-data:
 data:
 certs:
