version: '2'

services:

 proxy:
  image: vimagick/dante
  restart: always
  ports:
   - "1080:1080"

 nodepki:
  image: adito/nodepki-docker
  depends_on:
   - proxy
  volumes:
   - certs:/certs
   - data:/root/nodepki/data
   - data:/root/nodepki-client/data
   - data:/root/nodepki-webclient/data
   - ./docker-nodepki/applications/nodepki/data/config:/root/nodepki/data/config
   - ./docker-nodepki/applications/nodepki-client/data/config:/root/nodepki-client/data/config
   - ./docker-nodepki/applications/nodepki-webclient/data/config:/root/nodepki-webclient/data/config
   - ./docker-nodepki/applications/nodepki-webclient/api/webclient/controllers/request.js:/root/nodepki-webclient/controllers/request.js
   - ./conf/http_server.conf:/etc/supervisor/conf.d/http_server.conf
  environment:
   - API_USERNAME=${API_USERNAME}
   - API_PASSWORD=${API_PASSWORD}

 nexus:
  build: .
  restart: always
  command: ash -c "bin/nexus run"
  volumes:
   - nexus:${NEXUS_KEYSTORE}
   - certs:/certs
  environment:
   - NEXUS_KEYSTORE=/nexus-data
   - KEYSTOREPASSWORD=${KEYSTOREPASSWORD}
   - KEYMANAGERPASSWORD=${KEYMANAGERPASSWORD}
   - TRUSTSTOREPASSWORD=${TRUSTSTOREPASSWORD}
   - JKS_PASSWORD=${KEYSTOREPASSWORD}
  ports:
   - 443:443
   - 8443:8443
   - 8081:8081
   - 5000:5000

volumes:
 nexus:
 data:
 certs:
